
import java.util.*;


public class Hangman {
    public static Scanner input = new Scanner(System.in);
    public static ArrayList<Character> missedLetter = new ArrayList<>();
    public static ArrayList<Character> guessLetter = new ArrayList<>();
    public static Set<Character> missedCharacter = new HashSet<>();

    public static void main(String[] args) {

        System.out.println("\n HANGMAN \n\n");

        int randomLength = lengthofRandomWord();

        //Generate a guessLetter Array with DASH
        guessLetterInitDash(randomLength);
        guessLetterArrayPrint(randomLength);

        char randomChar[] = generateRandomWord(randomLength);
        String randomWord = String.valueOf(randomChar);
        System.out.println("Random Word Generated by Computer is " + Arrays.toString(randomChar) + "\n" + randomWord);

        int attempt = chance();
        int attempinit = attempt;

        while (attempt >= 0) {
            String guessedWord = "";
            System.out.println("Guess the Character in the String");
            char guessedChar = input.next().charAt(0);

            for (int x = 0; x < randomLength; x++) {

                if (guessedChar == randomWord.charAt(x)) {
                    guessLetter.set(x, guessedChar);
                }
            }

            if (guessLetter.indexOf(guessedChar) == -1) {
                missedCharacter.add(guessedChar);
            }

            System.out.println(guessLetter);
            System.out.println(missedCharacter);

            for (int y = 0; y < guessLetter.size(); y++) {
                guessedWord += guessLetter.get(y);
            }

            if (guessedWord.equals(randomWord)) {
                System.out.println("You Won!");
                attempt--;
                int totalAttempts = attempinit-attempt;
                System.out.println("You attempted " + totalAttempts + " times to guess the random word");
                System.exit(0);
            }
            attempt--;
            System.out.println("You lost the game after you have  " + attempt + " left after getting " + attempinit + " attempts ");
        }

//        welcomeinitHangmanGame();
    }

    public static int lengthofRandomWord() {
        System.out.println("Enter the length of Random word to be generated");
        int length = input.nextInt();
        return length;
    }

    public static void guessLetterInitDash(int num) {
        for (int i = 0; i < num; i++) {
            guessLetter.add('_');
        }
    }

    public static void guessLetterArrayPrint(int num){
        String temp1 = "";
        for (int j = 0; j < guessLetter.size(); j++) {
            System.out.println(guessLetter.get(j));
            temp1 += guessLetter.get(j);
        }
        System.out.println("+---+ \n\n" +
                "    | \n\n" +
                "    | \n\n" +
                "    | \n\n" +
                "    ===\n\n" +
                "Missed Letter : \n\n"
                + temp1 + "\n\n" +
                "Guess a Letter.\n\n");
        System.out.println();
    }

//    public static void guessLetterFillDash(int num){
//        System.out.println("Enter the attempt you want to make");
//        int attempt = input.nextInt();
//        while (attempt >= 0){
//            System.out.println("Guess the Character in the String");
//            String guessedChar = input.next();
//            for (int i = 0; i < num; i++){
//                if(random)
//            }
//        }
//    }


    public static char[] generateRandomWord(int numLength) {
        Random random = new Random();
        char[] word = new char[random.nextInt(1) + numLength];
        for (int j = 0; j < word.length; j++) {
            word[j] = (char) ('a' + random.nextInt(26));
        }
        return word;
    }

    public static int chance() {
        System.out.println("Enter the attempt you want to make");
        int chance = input.nextInt();
        return chance;
    }

//    public static void welcomeinitHangmanGame() {
//        System.out.println("+---+ \n\n" +
//                "    | \n\n" +
//                "    | \n\n" +
//                "    | \n\n" +
//                "    ===\n\n" +
//                "Missed Letter : \n\n" +
//                 "   \n\n" +
//                "Guess a Letter.\n\n");
//    }

}
//    https://www.geeksforgeeks.org/generate-random-string-of-given-size-in-java/

